fix TypeError (#82)
* fix TypeError

TypeError: Optional[t] requires a single type. Got (typing.Pattern, <class 'str'>).

* Adding `None` to signature of ETMChat.match(pattern)